### ISSUE TITLE
how can i use jodconverter to convert word to PDF/A format file?

### ISSUE THREAD

**Issue by cmanlh** [jodconverter/jodconverter#313]
![微信图片_20221107111328](https://user-images.githubusercontent.com/1443322/200218929-a3f077ff-2c12-4e21-a991-83d69c1b8718.jpg)

As the above picture, the libreoffice support export the word to as a PDF/A format file.  Does the jodconverter support this convertion options ? thanks.

**Comment by sbraconnier** [comment]
@cmanlh Is this question still relevant?

**Comment by shysteph** [comment]
@cmanlh If you are using spring boot autoconfiguration then this should work. Otherwise translate into store options.
```
# application.yml
jodconverter:
  local:
    format-options:
      pdf:
        store:
          TEXT:
            FilterData:
              SelectPdfVersion: 3
          DRAWING:
            FilterData:
              SelectPdfVersion: 3
          SPREADSHEET:
            FilterData:
              SelectPdfVersion: 3
          PRESENTATION:
            FilterData:
              SelectPdfVersion: 3
```
That specifically selects pdf/a-3 and requires a newish libreoffice. I am working on a PR to expose some of these settings in a more natural way inside jodconverter as it feels like controling pdf output options specifically is a thing a lot of people want. My team is having issues with html -> word after this but it seems to be a libreoffice version issue not anything to do with jodconverter.
