### ISSUE TITLE
No qualifying bean of type 'org.jodconverter.core.DocumentConverter' available

### ISSUE THREAD

**Issue by enlob** [jodconverter/jodconverter#390]
When running jodconverter on a spring boot project I get the error:

`Error creating bean with name '...': Unsatisfied dependency expressed through field 'documentConverter'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.jodconverter.core.DocumentConverter' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}`

pom.xml

```
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>2.6.3</version>
</parent>
...
<dependency>
    <groupId>org.jodconverter</groupId>
    <artifactId>jodconverter-local</artifactId>
    <version>4.4.7</version>
</dependency>
<dependency>
    <groupId>org.jodconverter</groupId>
    <artifactId>jodconverter-spring-boot-starter</artifactId>
    <version>4.4.7</version>
</dependency>
```

application.yml

```
jodconverter:
  local:
    enabled: true
    format-options:
      html:
        store:
          TEXT:
            FilterOptions: EmbedImages

      xhtml:
        store:
          TEXT:
            FilterOptions: EmbedImages
```

service.java

`@Autowired private DocumentConverter documentConverter;`
