### ISSUE TITLE
Running JOD Converter with PDF Export Command Line Parameters

### ISSUE THREAD

**Issue by joenmoreno** [jodconverter/jodconverter#419]
Hello, I am looking for ways to add command line parameters with JODConverter but I can't seem to find the correct way to do this. 
For example, I would like to run PDF Export parameters (as described here: https://help.libreoffice.org/latest/en-US/text/shared/guide/pdf_params.html) so that the converted PDF would be in the PDF/A-2b version and the standard fonts are embedded in the resulting PDF. To accomplish this using LibreOffice CLI, I would use the following command:

libreoffice25.2 --headless --invisible --nodefault --view \
        --nolockcheck --nologo --norestore --convert-to 'pdf:writer_pdf_Export:{"SelectPdfVersion":{"type":"long","value":"2"},"EmbedStandardFonts":{"type":"boolean","value":"true"}}' \
        --outdir /tmp /tmp/file-sample_1MB.doc

How do I accomplish the same using JODConverter? Is it through the jodconverter application.yml settings? If so, how?

JODConverter Version: 4.4.8
LibreOffice Java API Version: 24.8.4
Docker Image: Amazon Corretto 21 AMD 64
Java Version: Amazon Corretto 21
Spring Boot: 3.4.4
LibreOffice Installed in the Docker Image: 25.2.x

Just to clarify, my application is running and deployed in AWS ECS Fargate Tasks. I just needed to know how I can tweak the LibreOffice PDF Export (or possibly other Export) parameters other than the defaults.

**Comment by sbraconnier** [comment]
Here's an example:

```java
Map<String, Object> filterData = new HashMap<>();
filterData.put("SelectPdfVersion", 2);
filterData.put("EmbedStandardFonts", true);

Map<String, Object> storeProps = new HashMap<>();
storeProps.put("FilterData", filterData);

File inputFile = new File("/tmp/file-sample_1MB.doc");
File outputFile = new File("/tmp/file-sample_1MB.pdf");

LocalConverter
        .builder()
        .officeManager(manager)
        .storeProperties(storeProps)
        .build()
        .convert(inputFile)
        .to(outputFile)
        .execute();
```

**Comment by joenmoreno** [comment]
Sorry, I should have been more specific. I am currently Autowiring a DocumentConverter for my Service (inspired by spring-boot-webapp). You're example uses the LocalConverter.builder() with an Autowired OfficeManager (I assume), With DocumentConverter, I could not find a way to set storeProperties before I call convert on it. Is it an either/or? If I needed to add those FilterData options, then I need to use the LocalConverter.builder() + Autowired OfficeManager? And if I don't, I can use the Autowired DataConverter? My follow-up question to that would be "what kind of performance implications, if any, to consider in deciding to use one or the other?" Is LocalConverter.builder() + Autowired OfficeManager more performant? Or Autowired DocumentConverter more performant? Or are they the same?

TIA.

**Comment by sbraconnier** [comment]
Well, creating a converter is not a big deal, so you could use the LocalConverter.builder() + Autowired OfficeManager for each conversion. 

If you want to set the FilterData options from the application.yml, it would be like this:
```yml
# application.yml
jodconverter:
  local:
    format-options:
      pdf:
        store:
          TEXT:
            FilterData:
              SelectPdfVersion: 2
              EmbedStandardFonts: true
          DRAWING:
            FilterData:
              SelectPdfVersion: 2
              EmbedStandardFonts: true
          SPREADSHEET:
            FilterData:
              SelectPdfVersion: 2
              EmbedStandardFonts: true
          PRESENTATION:
            FilterData:
              SelectPdfVersion: 2
              EmbedStandardFonts: true
```
